version: "3"

services:
  desafio-api:
    image: bitnami/postgresql
    ports:
      - 5433:5433
    environment:
      - POSTGRES_USERNAME=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DATABASE=api
